### ISSUE TITLE
Summary: Exceeds expectations

### ISSUE THREAD

**Issue by martoio** [eileenoh/Desmoto#3]
Great job on the code! Your HTML is easy to read and check and your CSS is optimized so you don't have the obvious copy/pasting that could happen. The main issues I have with your code is the lack of sectioning in your HTML and the ambiguity in the class names.

In terms of improvements, I would suggest taking a look at the article about semantic HTML and trying to improve your HTML to make it more semantic (ie, meaningful). It seems like an irrelevant thing, but it's what makes your code stand out as professional.

If you are interested in learning more about some HTML/CSS best practices, check out some of the links below:
https://github.com/bendc/frontend-guidelines
http://learn.shayhowe.com/html-css/writing-your-best-code/

Great job on this project and keep up the good work!

**Comment by eileenoh** [comment]
Thank you for the feedback. I will read the articles and be more thoughtful about others looking at my code. I knew what I meant, but I can see where it would be confusing for someone else and myself too after a couple of weeks.
